package model;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlumnoCurso.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class AlumnoCurso {
	private ETipoEstadoMateria estado;
	private Materia materia;
	private Nota nota;
	
	public ETipoEstadoMateria getEstado() {
		return estado;
	}
	public void setEstado(ETipoEstadoMateria estado) {
		this.estado = estado;
	}
	public Materia getMateria() {
		return materia;
	}
	public void setMateria(Materia materia) {
		this.materia = materia;
	}
	
	
}
