package model;
import java.sql.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuatrimestre.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Cuatrimestre {
	private Date fechaInicio;
	private Date fechaFin;
}
