package model;

import java.util.List;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Curso.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//
@Entity
public class Curso {
	@ManyToOne
	private ItemGrilla horario;
	@ManyToOne
	private Profesor profesor;
	private String aula;
	@OneToMany
	private List<Alumno> alumnos;
	private Cuatrimestre cuatrimestre;
	@OneToMany
	private List<ItemListaDeEspera> listaDeEspera;
	private int Capacidad;
	@OneToMany
	private List<ItemHorarioCursada> horarioCursada;
	@ManyToOne
	private Materia materia;
	private String codigo;

	public Curso() {
		// TODO Auto-generated constructor stub
	}

	public ItemGrilla getHorario() {
		return horario;
	}

	public void setHorario(ItemGrilla horario) {
		this.horario = horario;
	}

	public Profesor getProfesor() {
		return profesor;
	}

	public void setProfesor(Profesor profesor) {
		this.profesor = profesor;
	}

	public String getAula() {
		return aula;
	}

	public void setAula(String aula) {
		this.aula = aula;
	}

	public List<Alumno> getAlumnos() {
		return alumnos;
	}

	public void setAlumnos(List<Alumno> alumnos) {
		this.alumnos = alumnos;
	}

	public Cuatrimestre getCuatrimestre() {
		return cuatrimestre;
	}

	public void setCuatrimestre(Cuatrimestre cuatrimestre) {
		this.cuatrimestre = cuatrimestre;
	}

	public List<ItemListaDeEspera> getListaDeEspera() {
		return listaDeEspera;
	}

	public void setListaDeEspera(List<ItemListaDeEspera> listaDeEspera) {
		this.listaDeEspera = listaDeEspera;
	}

	public int getCapacidad() {
		return Capacidad;
	}

	public void setCapacidad(int capacidad) {
		Capacidad = capacidad;
	}

	public List<ItemHorarioCursada> getHorarioCursada() {
		return horarioCursada;
	}

	public void setHorarioCursada(List<ItemHorarioCursada> horarioCursada) {
		this.horarioCursada = horarioCursada;
	}

	public Materia getMateria() {
		return materia;
	}

	public void setMateria(Materia materia) {
		this.materia = materia;
	}

	public String getCodigo() {
		return codigo;
	}

	public void setCodigo(String codigo) {
		this.codigo = codigo;
	}

}
