package model;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Curso.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//

public class Curso {
	private ItemGrilla horario;
	private Profesor profesor;
	private String aula;
	private List<Alumno> alumnos;
	private Cuatrimestre cuatrimestre;
	private List<ItemListaDeEspera> listaDeEspera;
	private int Capacidad;
	private List<ItemHorarioCursada> horarioCursada;
	private Materia materia;
	private String codigo;

}
