package model;
import java.sql.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DatosAlumno.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class DatosAlumno {
	private  String nombre;
	private  String apellido;
	public  String dni;
	public  Date fechaNacimiento;
	public  Date fechaInscripcion;
	public  String libreta;
	public  String domicilio;
	public  String telefono;
	public  String password;
}
