package model;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Grilla.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Grilla {
	public  String año;
	public  String cuatrimestre;
	public  List<ItemGrilla> grilla;
}
