package model;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemListaDeEspera.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//

@Entity
public class ItemListaDeEspera {
	@ManyToOne
	private Alumno alumno;
	private int nroOrden;

	public ItemListaDeEspera() {
		// TODO Auto-generated constructor stub
	}

	public Alumno getAlumno() {
		return alumno;
	}

	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}

	public int getNroOrden() {
		return nroOrden;
	}

	public void setNroOrden(int nroOrden) {
		this.nroOrden = nroOrden;
	}

}
