package model;

import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.ManyToOne;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemGrilla.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//

@Entity
public class ItemGrilla {
	@ManyToOne
	public Curso curso;
	public String diaSemana;
	public Date horarioInicio;
	public Date horarioFinal;

	public ItemGrilla() {
		// TODO Auto-generated constructor stub
	}

	public Curso getCurso() {
		return curso;
	}

	public void setCurso(Curso curso) {
		this.curso = curso;
	}

	public String getDiaSemana() {
		return diaSemana;
	}

	public void setDiaSemana(String diaSemana) {
		this.diaSemana = diaSemana;
	}

	public Date getHorarioInicio() {
		return horarioInicio;
	}

	public void setHorarioInicio(Date horarioInicio) {
		this.horarioInicio = horarioInicio;
	}

	public Date getHorarioFinal() {
		return horarioFinal;
	}

	public void setHorarioFinal(Date horarioFinal) {
		this.horarioFinal = horarioFinal;
	}

}
