package model;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemListaDeEspera.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class ItemListaDeEspera {
	private Alumno alumno;
	private int nroOrden;
}
