package model;

import javax.persistence.Entity;
import javax.persistence.Enumerated;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemCursada.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//



@Entity
public class ItemHorarioCursada {
	@Enumerated
	private EDia dia;
	@Enumerated
	private EHoraCatedra desde;
	@Enumerated
	private EHoraCatedra hasta;
	public ItemHorarioCursada() {
		// TODO Auto-generated constructor stub
	}
	
	public EDia getDia() {
		return dia;
	}
	public void setDia(EDia dia) {
		this.dia = dia;
	}
	public EHoraCatedra getDesde() {
		return desde;
	}
	public void setDesde(EHoraCatedra desde) {
		this.desde = desde;
	}
	public EHoraCatedra getHasta() {
		return hasta;
	}
	public void setHasta(EHoraCatedra hasta) {
		this.hasta = hasta;
	}
	
	
}
