package model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemCursada.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class ItemHorarioCursada {
	private EDia dia;
	private EHoraCatedra desde;
	private EHoraCatedra hasta;
}
