package model;
import java.util.List;
import java.util.Vector;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Materia.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Materia {
	public List<Materia> correlativas;
	public List<Curso> cursosMateria;
	public int horasCatedra;
	public List<Profesor> profesoresHab;
	
	public void planVigente() {
	
	}
}
