package model;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Materia.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//

@Entity
public class Materia extends BaseEntity<Long> {
	
	@OneToMany(fetch=FetchType.EAGER) @JoinColumn
	private Set<Materia> correlativas;
	@OneToMany(fetch=FetchType.EAGER) @JoinColumn
	private Set<Curso> cursosMateria;
	private int horasCatedra;
	@OneToMany(fetch=FetchType.EAGER) @JoinColumn
	private Set<Profesor> profesoresHab;
	private String nombre;
	
	@Id
	@GeneratedValue
	private Long id;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	
	public Materia() {
		// TODO Auto-generated constructor stub
	}

	public Set<Materia> getCorrelativas() {
		return correlativas;
	}

	public void setCorrelativas(Set<Materia> correlativas) {
		this.correlativas = correlativas;
	}

	public Set<Curso> getCursosMateria() {
		return cursosMateria;
	}

	public void setCursosMateria(Set<Curso> cursosMateria) {
		this.cursosMateria = cursosMateria;
	}

	public int getHorasCatedra() {
		return horasCatedra;
	}

	public void setHorasCatedra(int horasCatedra) {
		this.horasCatedra = horasCatedra;
	}

	public Set<Profesor> getProfesoresHab() {
		return profesoresHab;
	}

	public void setProfesoresHab(Set<Profesor> profesoresHab) {
		this.profesoresHab = profesoresHab;
	}

	public void planVigente() {

	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}
	
	
}
