package model;
import java.sql.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nota.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Nota {
	private ETipoNota tipo;
	private Date fechaAprobacion;
	private int nota;
}
