package model;
import java.util.List;

import javax.persistence.Enumerated;
import javax.persistence.OneToMany;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Plan.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Plan {
	private Integer Año;
	@OneToMany
	private List<Materia> materias;
	@Enumerated
	private EEstadoPlan Estado;
	
	public Plan() {
		// TODO Auto-generated constructor stub
	}

	public Integer getAño() {
		return Año;
	}

	public void setAño(Integer año) {
		Año = año;
	}

	public List<Materia> getMaterias() {
		return materias;
	}

	public void setMaterias(List<Materia> materias) {
		this.materias = materias;
	}

	public EEstadoPlan getEstado() {
		return Estado;
	}

	public void setEstado(EEstadoPlan estado) {
		Estado = estado;
	}
	
	
}
