package model;
import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.Enumerated;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

import enumerates.EEstadoPlan;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Plan.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//



@Entity
public class Plan extends BaseEntity<Long> {
	private Integer Año;
	@OneToMany(fetch=FetchType.EAGER) @JoinColumn
	private Set<Materia> materias;
	@Enumerated
	private EEstadoPlan Estado;
	
	@Id
	@GeneratedValue
	private Long id;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	
	public Plan() {
		// TODO Auto-generated constructor stub
	}

	public Integer getAño() {
		return Año;
	}

	public void setAño(Integer año) {
		Año = año;
	}

	public Set<Materia> getMaterias() {
		return materias;
	}

	public void setMaterias(Set<Materia> materias) {
		this.materias = materias;
	}

	public EEstadoPlan getEstado() {
		return Estado;
	}

	public void setEstado(EEstadoPlan estado) {
		Estado = estado;
	}
	
	
}
