package model;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Plan.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Plan {
	private Integer Año;
	private List<Materia> materias;
	private EEstadoPlan Estado;
}
