package model;
import java.util.List;

import javax.persistence.Entity;
import javax.persistence.OneToMany;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Profesor.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//



@Entity
public class Profesor extends Usuario{
	@OneToMany
	public List<Curso> cursosProfesor;

	public Profesor() {
		super();
	}
	
	@Override
	public String getRol() {
		return "Profesor";
	}
}
