package model;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Profesor.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Profesor extends Usuario{
	public List<Curso> cursosProfesor;

	@Override
	public String getRol() {
		return "Profesor";
	}
}
