package model;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Regente.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Regente extends Usuario{
	
	@Override
	public String getRol(){
		return "Regente";
	}
}
