package model;

import javax.persistence.Entity;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Regente.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//



@Entity
public class Regente extends Usuario{
	
	public Regente() {
		super();
	}
	
	@Override
	public String getRol(){
		return "Regente";
	}
}
