package model;

import java.sql.Date;

import javax.persistence.Entity;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Reporte.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//
import javax.persistence.GeneratedValue;
import javax.persistence.Id;



@Entity
public class Reporte {
	private Date fecha;
	private Byte[] archivoReporte;
	
	@Id
	@GeneratedValue
	private Long id;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	
	public Reporte() {
		// TODO Auto-generated constructor stub
	}

	public Date getFecha() {
		return fecha;
	}

	public void setFecha(Date fecha) {
		this.fecha = fecha;
	}

	public Byte[] getArchivoReporte() {
		return archivoReporte;
	}

	public void setArchivoReporte(Byte[] archivoReporte) {
		this.archivoReporte = archivoReporte;
	}
	
}
