package model;

import java.sql.Date;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AlumnoPlan.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class AlumnoPlan {
	private Plan plan;
	private Alumno alumno;
	private EEstado estado;
	private Date fechaAlta;
	private Date fechaFin;
	public Plan getPlan() {
		return plan;
	}
	public void setPlan(Plan plan) {
		this.plan = plan;
	}
	public Alumno getAlumno() {
		return alumno;
	}
	public void setAlumno(Alumno alumno) {
		this.alumno = alumno;
	}
	public EEstado getEstado() {
		return estado;
	}
	public void setEstado(EEstado estado) {
		this.estado = estado;
	}
	public Date getFechaAlta() {
		return fechaAlta;
	}
	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}
	public Date getFechaFin() {
		return fechaFin;
	}
	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}
	
	
}
