package model;

import java.sql.Date;
import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Alumno.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Alumno extends Usuario{
	private List<AlumnoPlan> alumnoPlanes;
	private List<AlumnoCurso> alumnoCursos;
	private Integer prioridad;
	public Date fechaNacimiento ;
	private Date fechaInscripcion ;
	private String nroLibreta ;
	private EEstado estado;
	private String direccion;
	private String telefono;
	private String sexo;
	private String nacionalidad;
	
	
	@Override
	public String getRol() {
		// TODO Auto-generated method stub
		return null;
	}
	
	
	
	
}
