package model;

import java.util.List;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Carrera.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class Carrera {
	public String nombre;
	public List<Plan> curricula;
}
