package model;
import java.sql.Date;

import javax.persistence.Entity;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuatrimestre.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//



@Entity
public class Cuatrimestre {
	private Date fechaInicio;
	private Date fechaFin;
	public Cuatrimestre() {
		// TODO Auto-generated constructor stub
	}
	public Date getFechaInicio() {
		return fechaInicio;
	}
	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}
	public Date getFechaFin() {
		return fechaFin;
	}
	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}
	
}
