package model;
import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.EnumType;
import javax.persistence.Enumerated;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;

import enumerates.ETipoCuatrimestre;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Cuatrimestre.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//



@Entity
public class Cuatrimestre extends BaseEntity<Long> {
	private Date fechaInicio;
	private Date fechaFin;
	@Enumerated(EnumType.ORDINAL)
	private ETipoCuatrimestre tipoCuatrimestre;
	private int año;
	@Id
	@GeneratedValue
	private Long id;
	
	private boolean activo;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Cuatrimestre() {
		// TODO Auto-generated constructor stub
	}
	public Date getFechaInicio() {
		return fechaInicio;
	}
	public void setFechaInicio(Date fechaInicio) {
		this.fechaInicio = fechaInicio;
	}
	public Date getFechaFin() {
		return fechaFin;
	}
	public void setFechaFin(Date fechaFin) {
		this.fechaFin = fechaFin;
	}

	public ETipoCuatrimestre getTipoCuatrimestre() {
		return tipoCuatrimestre;
	}

	public void setTipoCuatrimestre(ETipoCuatrimestre tipoCuatrimestre) {
		this.tipoCuatrimestre = tipoCuatrimestre;
	}

	public int getAño() {
		return año;
	}

	public void setAño(int año) {
		this.año = año;
	}

	public boolean isActivo() {
		return activo;
	}

	public void setActivo(boolean activo) {
		this.activo = activo;
	}

	
	

	
}
