package model;

import java.util.Set;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Grilla.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//

@Entity
public class Grilla {
	public String año;
	public String cuatrimestre;
	@OneToMany(fetch=FetchType.EAGER) @JoinColumn
	public Set<ItemGrilla> grilla;
	@Id
	@GeneratedValue
	private Long id;
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
	
	public Grilla() {
		// TODO Auto-generated constructor stub
	}

	public String getAño() {
		return año;
	}

	public void setAño(String año) {
		this.año = año;
	}

	public String getCuatrimestre() {
		return cuatrimestre;
	}

	public void setCuatrimestre(String cuatrimestre) {
		this.cuatrimestre = cuatrimestre;
	}

	public Set<ItemGrilla> getGrilla() {
		return grilla;
	}

	public void setGrilla(Set<ItemGrilla> grilla) {
		this.grilla = grilla;
	}

}
