package model;

import java.sql.Date;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : ItemGrilla.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class ItemGrilla {
	public  Curso curso;
	public  String diaSemana;
	public  Date horarioInicio;
	public  Date horarioFinal;
}
