package model;
import java.sql.Date;

import javax.persistence.Entity;
import javax.persistence.Enumerated;

//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Nota.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//



@Entity
public class Nota {
	@Enumerated
	private ETipoNota tipo;
	private Date fechaAprobacion;
	private int nota;
	
	public Nota() {
		// TODO Auto-generated constructor stub
	}

	public ETipoNota getTipo() {
		return tipo;
	}

	public void setTipo(ETipoNota tipo) {
		this.tipo = tipo;
	}

	public Date getFechaAprobacion() {
		return fechaAprobacion;
	}

	public void setFechaAprobacion(Date fechaAprobacion) {
		this.fechaAprobacion = fechaAprobacion;
	}

	public int getNota() {
		return nota;
	}

	public void setNota(int nota) {
		this.nota = nota;
	}
	
	
}
