package app;

import model.Usuario;
//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Sistema.java
//  @ Date : 28/08/2014
//  @ Author : 
//
//




public class SistemaOrig {
	/*public  List<Materia> materias;
	public  Vector<Carrera> carreras;
	public  Vector<Alumno> alumnos;
	public  Vector<Profesor> profesores;
	public  Vector<Curso> cursos;
	private Vector<Reporte> reportes;
	private Vector<Incripcion> inscripciones;
	private Vector<Cuatrimestre> cuatrimestres;
	private Object grillaHoraria;
	private Object regente Regente;
	public Cuatrimestre getCuatrimestreActual() {
	
	}*/
	
	
	public Usuario login(String documento, String password){
		return UserDao.getUsuarioByDocumentoAndPasssword(documento, password);
	}
	
	public void abrirInscripciones() {
	
	}
	
	public void ingresarFechaInicio(Object fecha date) {
	
	}
	
	public void validarFechaInicio(fecha Date):Boolean() {
	
	}
	
	public void calcularFechaCierre( FechaI Date): Date() {
	
	}
	
	public void buscarAlumno(Object nombre String) {
	
	}
	
	public void enviarEMailFI(Object email String, Object Fecha Date) {
	
	}
	
	public void creacionCursos() {
	
	}
	
	public void generarInfoCursosCCSVyPDF() {
	
	}
	
	public void gestionarInscripcionAlumno(Object Alumno String, Object Pass String) {
	
	}
	
	
	public void BuscarCursoxMateria(Object materia String) {
	
	}
	
	public boolean inscripcionMateria(Object idAlumno String, Object codigo String) {
	
	}
	
	private void validarAlumonCruso() {
	
	}
	
	public void buscarCursoxAlumno(Object alumno String) {
	
	}
	
	public void generarReporteAlumnos() {
	
	}
	
	private void generarPDFReporteAlumnos() {
	
	}
	
	public void generarReporteCursos() {
	
	}
	
	private void generarPDFReporteCurso():Void() {
	
	}
	
	public Void() generarPDFReporteListaEspera() {
	
	}
	
	public void generarReporteListaEspera():void() {
	
	}
}
